#!/bin/sh -e

if [ "$1" = remove ]; then
        update-alternatives --remove global-assembly-cache-tool /usr/bin/gacutil
        
        # Remove the GAC
        if [ -x /usr/share/cli-common/gac-remove ]; then
		/usr/share/cli-common/gac-remove mono
	fi

	# Remove any framework libs
        if [ -x /usr/share/cli-common/framework-remove ]; then
		/usr/share/cli-common/framework-remove mono
	fi
fi

#DEBHELPER#
