#!/bin/sh
set -e

if [ ! -x /usr/lib/monodoc/browser.exe -o -z "$(dpkg-query -W -f='${Status}' monodoc-browser 2>/dev/null | grep "ok installed")" ]; then
	exit 0
fi

echo "generating monodoc search index..."
monodoc --make-index > /dev/null

echo "generating monodoc search index... (this can take a while)"
monodoc --make-search-index > /dev/null
